### ISSUE TITLE
[Suggestion] Config options to adjust what potion effects the polluted water gives

### ISSUE THREAD

**Issue by RedRaspberry** [BananaFructa/UnecologicalMethods#5]
I'm thinking about using this mod in a pack I'm making, but nausea IV quite literally makes my head hurt to look at. Any chance that there could be options to disable the potion effects or allow them to be changed in the config? This could also be useful to allow pack devs to do things such as give the fluid effects added by IE, like flammable and fluxed

**Comment by BananaFructa** [comment]
Did not think about that, will add.

**Comment by BananaFructa** [comment]
Done !
